name: Static analysis and coverage

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  analyze:
    uses: przemek83/workflows/.github/workflows/static-analysis-and-coverage-csharp.yml@main
    with:
      sonar_project_key: ${{ github.repository_owner }}_${{ github.event.repository.name }}
      sonar_organization: ${{ github.repository_owner }}
    secrets: inherit
