name: Static analysis and coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    uses: przemek83/workflows/.github/workflows/static-analysis-and-coverage-csharp.yml@main
    secrets: inherit